# ===============================
# GigaChat
# ===============================
spring.application.name=agent

spring.ai.gigachat.auth.bearer.api-key=${GIGA_CHAT_API_KEY}
spring.ai.gigachat.auth.scope=${GIGA_CHAT_SCOPE:GIGACHAT_API_PERS}
spring.ai.gigachat.chat.options.model=${GIGA_CHAT_MODEL:GigaChat-Pro}
logging.level.org.springframework.ai=${LOG_LEVEL_SPRING_AI:DEBUG}
logging.level.chat.giga=${LOG_LEVEL_GIGA:DEBUG}
spring.ai.gigachat.auth.unsafe-ssl=${GIGA_CHAT_UNSAFE_SSL:true}

# ===============================
# БД
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/agentdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${DB_SHOW_SQL:true}
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${DB_FORMAT_SQL:true}

# ===============================
# Приложение
# ===============================
app.max.cycles=${APP_MAX_CYCLES:5}
app.batch.size=${APP_BATCH_SIZE:5}
app.flat.limit=${APP_FLAT_LIMIT:5}
app.logging.slow-threshold-ms=${APP_SLOW_THRESHOLD_MS:60000}
app.logging.slow-scoring-threshold-ms=${APP_SLOW_SCORING_THRESHOLD_MS:20000}
app.timeout.reminder-wait-minutes=${APP_TIMEOUT_REMINDER_WAIT_MINUTES:300000}
app.data.apartments=${APP_DATA_APARTMENTS:data/apartments.json}
app.data.complexes=${APP_DATA_COMPLEXES:data/complexes.json}
app.timeout.scheduler=${APP_TIMEOUT_SCHEDULER:10}
app.resource.path=${APP_OFFER_TEMPLATE:templates/offer_template.txt}
app.prompt.path=${APP_SYSTEM_PROMPT:prompts/system_instruction.txt}
app.offer.pdf-template-path=${APP_OFFER_TEMPLATE:templates/offer_template.html}
app.offer.pdf-font-path=${APP_OFFER_FONT_PATH:fonts/DejaVuSans.ttf}
app.offer.pdf-font-family=${APP_OFFER_FONT_FAMILY:DejaVuSans}

# ===============================
# API
# ===============================
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
