# ===============================
# GigaChat
# ===============================
spring.application.name=agent

spring.ai.gigachat.auth.bearer.api-key=***
spring.ai.gigachat.auth.scope=GIGACHAT_API_PERS
spring.ai.gigachat.chat.options.model=GigaChat-Pro
logging.level.org.springframework.ai=DEBUG
logging.level.chat.giga=DEBUG
spring.ai.gigachat.auth.unsafe-ssl=true

# ===============================
# БД
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/agentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Приложение
# ===============================

app.max.cycles=5
app.batch.size=5
app.flat.limit=5
app.logging.slow-threshold-ms=60000
app.logging.slow-scoring-threshold-ms=20000
app.timeout.reminder-wait-minutes=300000
app.data.apartments=data/apartments.json
app.timeout.scheduler=10
app.resource.path=templates/offer_template.txt
app.prompt.path=prompts/system_instruction.txt